blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/devnonla/nonla-agents/discussions
    about: Please ask questions, share tips, or discuss Nonla Agents here.
